### ISSUE TITLE
DB interactions prone to SQL injection

### ISSUE THREAD

**Issue by bLittle1996** [omfgtora/Todo#1]
Look into [prepared statements](http://php.net/manual/en/pdo.prepared-statements.php)

**Comment by erobertsme** [comment]
Thank you! This is the plan to get to that point, but I am building the foundation of my understanding before applying PDO prepared statements so I can more effectively prepare and sanitize my statements.

**Comment by erobertsme** [comment]
I believe I have updated the statements to implement proper prepared statements in the [latest commit](https://github.com/omfgtora/Todo/commit/69ccc91152f54283bac66afc9fb405d3e4356ba3#diff-4f13205c57f0d3b4b9b2f1d6ccd9d4f4).

If I did not implement this correctly please reopen this issue.

**Comment by bLittle1996** [comment]
\o/
